### PR TITLE
Set background color for content container

### PR DESCRIPTION
**Pull request by JonesChi**

### CODE REVIEW

**Comment by orhanobut** [comment]
That would change the behavior. Currently backgroundcolor is used for holder container which is list,grid or custom one. ContentContainer should be transparent.

**Comment by JonesChi** [comment]
Ok, so I think it would need another API to set the background for the ContentContainer. If the expanded enabled, and the list only has one or two items, then the UI would look weird when the dialog expanded with transparent background.

**Comment by orhanobut** [comment]
Yes, definitely need another API to change the contentcontainer background. Would be great to have it.

**Comment by orhanobut** [comment]
closing this PR as explained in the pr comments

**Pull request closed without merging**
