### PR TITLE
Exception handler added to setClickListener

### PR DESCRIPTION
**Pull request by Euphrates-Media**
This is needed when content was infalted layout.

### CODE REVIEW

**Comment by yekmer** [comment]
Hi,

Using try catch on an unknown situation does not seems a good way of handling errors. If there is an error on some line of code, we can fix it in exact place instead of try catching all function

**Comment by Euphrates-Media** [comment]
When I try to use an infalted view in dialogplus these lines make error exceptions...

**Comment by yekmer** [comment]
I saw your issue but could not figured out a solution for it. May be Orhan can help you

**Comment by orhanobut** [comment]
As Yekmer said, try catch will just ignore the real issue but the problem will be still there. The problem is actually dialogplus tries to put a different parent to the view but the view already has a parent.

**Pull request closed without merging**
