### PR TITLE
Add Jitpack.io support

### PR DESCRIPTION
**Pull request by almozavr**
For easy forking/publishing and snapshoting

### CODE REVIEW

**Comment by orhanobut** [comment]
How does it work? I'm curious about the advantages, sorry for late reply btw

**Comment by almozavr** [comment]
E.g. forks doesn't have to provide own repo but for artifacts but is already available via jitpack.io, like `compile com.github.forkeeboy:dialogplus:hashcommit`

**Comment by orhanobut** [comment]
Sorry for late reply, was in vacation, can you please resolve the conflict? then we can merge it, jitpack seems very nice

**Comment by almozavr** [comment]
@orhanobut done.

**Comment by orhanobut** [comment]
Perfect, thanks!

**Pull request merged**
